# Markdownlint configuration
extends: null
rules:
  # Disable line length checking
  MD013: false

  # Allow duplicate headings in different sections
  MD024:
    siblings_only: true

  # Allow inline HTML (for badges, etc.)
  MD033: false

  # Allow trailing punctuation in headings
  MD026: false

  # Allow multiple top-level headings
  MD025: false

  # Allow emphasis used instead of headings
  MD036: false

  # Allow code fences without language (for plain text examples)
  MD040: false
