- id: helm-lint
  name: Helm Lint
  description: Run helm lint on Helm charts
  entry: hooks/helm-lint.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-template
  name: Helm Template
  description: Validate Helm chart templates
  entry: hooks/helm-template.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-unittest
  name: Helm Unit Tests
  description: Run Helm unit tests
  entry: hooks/helm-unittest.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|.*\.tpl|tests/.*\.yaml)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-docs
  name: Helm Docs
  description: Generate/update Helm chart documentation
  entry: hooks/helm-docs.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|README\.md)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-security
  name: Helm Security Scan
  description: Security scan for Helm charts using Trivy
  entry: hooks/helm-security.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-dependency-update
  name: Helm Dependency Update
  description: Update Helm chart dependencies
  entry: hooks/helm-dependency-update.sh
  language: script
  files: '(Chart\.yaml|Chart\.lock)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-kubeval
  name: Helm Kubeval
  description: Validate Kubernetes manifests generated by Helm
  entry: hooks/helm-kubeval.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false
