- id: helm-lint
  name: Helm Lint
  description: Run helm lint on Helm charts
  entry: hooks/helm-lint.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-template
  name: Helm Template
  description: Validate Helm chart templates
  entry: hooks/helm-template.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-unittest
  name: Helm Unit Tests
  description: Run Helm unit tests
  entry: hooks/helm-unittest.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|.*\.tpl|tests/.*\.yaml)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-docs
  name: Helm Docs
  description: Generate/update Helm chart documentation
  entry: hooks/helm-docs.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|README\.md)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-security
  name: Helm Security Scan
  description: Security scan for Helm charts using Trivy
  entry: hooks/helm-security.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-dependency-update
  name: Helm Dependency Update
  description: Update Helm chart dependencies
  entry: hooks/helm-dependency-update.sh
  language: script
  files: '(Chart\.yaml|Chart\.lock)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-kubeconform
  name: Helm Kubeconform
  description: Validate Kubernetes manifests generated by Helm using kubeconform
  entry: hooks/helm-kubeconform.sh
  language: script
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false

# Docker-based hooks (recommended)
- id: helm-lint-docker
  name: Helm Lint (Docker)
  description: Run helm lint on Helm charts using Docker
  entry: ghcr.io/jorisdejosselin/pre-commit-helm:latest
  language: docker_image
  args: ["-c", "/usr/local/bin/helm-lint.sh"]
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-template-docker
  name: Helm Template (Docker)
  description: Validate Helm chart templates using Docker
  entry: ghcr.io/jorisdejosselin/pre-commit-helm:latest
  language: docker_image
  args: ["-c", "/usr/local/bin/helm-template.sh"]
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-unittest-docker
  name: Helm Unit Tests (Docker)
  description: Run Helm unit tests using Docker
  entry: ghcr.io/jorisdejosselin/pre-commit-helm:latest
  language: docker_image
  args: ["-c", "/usr/local/bin/helm-unittest.sh"]
  files: '(Chart\.yaml|values\.yaml|.*\.tpl|tests/.*\.yaml)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-docs-docker
  name: Helm Docs (Docker)
  description: Generate/update Helm chart documentation using Docker
  entry: ghcr.io/jorisdejosselin/pre-commit-helm:latest
  language: docker_image
  args: ["-c", "/usr/local/bin/helm-docs.sh"]
  files: '(Chart\.yaml|values\.yaml|README\.md)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-security-docker
  name: Helm Security Scan (Docker)
  description: Security scan for Helm charts using Trivy in Docker
  entry: ghcr.io/jorisdejosselin/pre-commit-helm:latest
  language: docker_image
  args: ["-c", "/usr/local/bin/helm-security.sh"]
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-dependency-update-docker
  name: Helm Dependency Update (Docker)
  description: Update Helm chart dependencies using Docker
  entry: ghcr.io/jorisdejosselin/pre-commit-helm:latest
  language: docker_image
  args: ["-c", "/usr/local/bin/helm-dependency-update.sh"]
  files: '(Chart\.yaml|Chart\.lock)$'
  require_serial: false
  pass_filenames: false
  always_run: false

- id: helm-kubeconform-docker
  name: Helm Kubeconform (Docker)
  description: Validate Kubernetes manifests generated by Helm using kubeconform in Docker
  entry: ghcr.io/jorisdejosselin/pre-commit-helm:latest
  language: docker_image
  args: ["-c", "/usr/local/bin/helm-kubeconform.sh"]
  files: '(Chart\.yaml|values\.yaml|.*\.tpl)$'
  require_serial: false
  pass_filenames: false
  always_run: false
