# Advanced .pre-commit-config.yaml for Helm projects with CI/CD pipeline

repos:
  - repo: https://github.com/jorisdejosselin/pre-commit-helm
    rev: v1.0.0
    hooks:
      # Validation hooks
      - id: helm-lint
        args: ["--strict"]
        stages: [commit, push]

      - id: helm-template
        args: ["--debug"]
        stages: [commit, push]

      # Testing hooks
      - id: helm-unittest
        args: ["--color", "--output-type", "JUnit"]
        stages: [commit]

      # Security and compliance
      - id: helm-security
        args: ["--severity", "HIGH,CRITICAL", "--format", "json"]
        stages: [push]

      - id: helm-kubeval
        args: ["--kubernetes-version", "1.28.0", "--strict"]
        stages: [push]

      # Documentation and dependencies
      - id: helm-docs
        args:
          [
            "--sort-values-order",
            "file",
            "--template-files",
            "README.md.gotmpl",
          ]
        stages: [commit]

      - id: helm-dependency-update
        stages: [commit]

  # Code quality hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types: [yaml]
        exclude: 'templates/.*\.yaml$'
